#cloud-config
packages:
  - jq

write_files:
  # - path: /etc/vault.d/vault.conf
  #   content: ${vault_conf}
  #   permissions: '0644'
  #   owner: vault:vault
  #   encoding: b64
  - path: /etc/environment
    content: |
      VAULT_ADDR=http://127.0.0.1:8200
    append: true

runcmd:
  - sudo systemctl enable vault
  - sudo systemctl restart vault
